version: '3.4'

services:
  testforpanel:
    image: testforpanel
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
